import GroupBudget from '../models/GroupBudget.js';
import Expense from '../models/Expense.js';
import { User } from '../models/index.js';
import { BadRequestError, NotFoundError, ForbiddenError, successResponse } from '../middleware/errorHandler.js';
import mongoose from 'mongoose';

/**
 * @desc    Create new group budget (independent, no Group required)
 * @route   POST /api/group-budgets
 * @access  Private
 */
export const createGroupBudget = async (req, res) => {
  const userId = req.userId;
  const { name, description, totalBudget, currency, startDate, endDate, members, autoSplitByContribution, allowPartialTag } = req.body;

  try {
    // Validate members
    if (!members || members.length === 0) {
      throw new BadRequestError('Phải có ít nhất 1 thành viên');
    }

    // Validate total percentage = 100
    const totalPercentage = members.reduce((sum, m) => sum + m.contributionPercentage, 0);
    if (Math.abs(totalPercentage - 100) > 0.01) {
      throw new BadRequestError(`Tổng phần trăm đóng góp phải bằng 100%. Hiện tại: ${totalPercentage}%`);
    }

    // Get member names from User collection
    const memberIds = members.map(m => m.userId);
    const users = await User.find({ _id: { $in: memberIds } }).select('profile.name email');

    const membersWithNames = members.map(m => {
      const user = users.find(u => u._id.toString() === m.userId.toString());
      return {
        userId: m.userId,
        name: m.name || user?.profile?.name || user?.email || 'Unknown',
        contributionPercentage: m.contributionPercentage,
      };
    });

    // Create group budget (invite code will be auto-generated by pre-save)
    const groupBudget = new GroupBudget({
      createdBy: userId,
      name,
      description,
      totalBudget,
      currency: currency || 'VND',
      startDate: startDate || new Date(),
      endDate,
      members: membersWithNames,
      autoSplitByContribution: autoSplitByContribution !== undefined ? autoSplitByContribution : true,
      allowPartialTag: allowPartialTag !== undefined ? allowPartialTag : true,
    });

    await groupBudget.save();

    successResponse(res, 'Tạo GroupBudget thành công', groupBudget, 201);
  } catch (error) {
    console.error('❌ Create GroupBudget error:', error);
    if (error instanceof BadRequestError || error instanceof NotFoundError) {
      throw error;
    }
    throw new BadRequestError(error.message);
  }
};

/**
 * @desc    Get all group budgets for current user
 * @route   GET /api/group-budgets
 * @access  Private
 */
export const getGroupBudgets = async (req, res) => {
  const userId = req.userId;
  const { isActive, isSettled } = req.query;

  try {
    const filter = {
      'members.userId': userId,
    };

    if (isActive !== undefined) {
      filter.isActive = isActive === 'true';
    }
    if (isSettled !== undefined) {
      filter.isSettled = isSettled === 'true';
    }

    const budgets = await GroupBudget.find(filter)
      .populate('createdBy', 'profile.name email')
      .populate('members.userId', 'profile.name email')
      .sort({ createdAt: -1 });

    successResponse(res, 'Lấy danh sách GroupBudget thành công', budgets);
  } catch (error) {
    console.error('❌ Get GroupBudgets error:', error);
    throw new BadRequestError(error.message);
  }
};

/**
 * @desc    Get group budget by ID
 * @route   GET /api/group-budgets/:id
 * @access  Private
 */
export const getGroupBudgetById = async (req, res) => {
  const userId = req.userId;
  const { id } = req.params;

  try {
    const groupBudget = await GroupBudget.findById(id)
      .populate('createdBy', 'profile.name email')
      .populate('members.userId', 'profile.name email')
      .populate('expenses.paidBy', 'profile.name email');

    if (!groupBudget) {
      throw new NotFoundError('Không tìm thấy GroupBudget');
    }

    // Check if user is member
    const isMember = groupBudget.members.some(m => m.userId._id.toString() === userId.toString());
    if (!isMember) {
      throw new ForbiddenError('Bạn không phải thành viên của budget này');
    }

    successResponse(res, 'Lấy thông tin GroupBudget thành công', groupBudget);
  } catch (error) {
    console.error('❌ Get GroupBudget error:', error);
    if (error instanceof NotFoundError || error instanceof ForbiddenError) {
      throw error;
    }
    throw new BadRequestError(error.message);
  }
};

/**
 * @desc    Join group budget by invite code
 * @route   POST /api/group-budgets/join
 * @access  Private
 */
export const joinGroupBudget = async (req, res) => {
  const userId = req.userId;
  const { inviteCode, contributionPercentage } = req.body;

  try {
    if (!inviteCode) {
      throw new BadRequestError('Invite code là bắt buộc');
    }

    // Find budget by invite code
    const groupBudget = await GroupBudget.findOne({ inviteCode: inviteCode.toUpperCase() });
    if (!groupBudget) {
      throw new NotFoundError('Không tìm thấy GroupBudget với mã này');
    }

    if (!groupBudget.isActive) {
      throw new BadRequestError('GroupBudget này không còn hoạt động');
    }

    // Get user info
    const user = await User.findById(userId).select('profile.name email');
    if (!user) {
      throw new NotFoundError('Không tìm thấy user');
    }

    const userName = user.profile?.name || user.email || 'Unknown';

    // Add member to budget
    groupBudget.addMember(userId, userName, contributionPercentage || 0);
    await groupBudget.save();

    successResponse(res, 'Tham gia GroupBudget thành công', groupBudget, 200);
  } catch (error) {
    console.error('❌ Join GroupBudget error:', error);
    if (error instanceof BadRequestError || error instanceof NotFoundError) {
      throw error;
    }
    throw new BadRequestError(error.message);
  }
};

/**
 * @desc    Invite user to group budget by email or userId
 * @route   POST /api/group-budgets/:id/invite
 * @access  Private
 */
export const inviteToGroupBudget = async (req, res) => {
  const userId = req.userId;
  const { id } = req.params;
  const { email, inviteUserId, contributionPercentage } = req.body;

  try {
    const groupBudget = await GroupBudget.findById(id);
    if (!groupBudget) {
      throw new NotFoundError('Không tìm thấy GroupBudget');
    }

    // Check if requester is member
    const isMember = groupBudget.members.some(m => m.userId.toString() === userId.toString());
    if (!isMember) {
      throw new ForbiddenError('Bạn không phải thành viên của budget này');
    }

    // Find user to invite
    let invitedUser;
    if (inviteUserId) {
      invitedUser = await User.findById(inviteUserId).select('profile.name email');
    } else if (email) {
      invitedUser = await User.findOne({ email }).select('profile.name email');
    } else {
      throw new BadRequestError('Cần provide email hoặc userId');
    }

    if (!invitedUser) {
      throw new NotFoundError('Không tìm thấy user để invite');
    }

    const userName = invitedUser.profile?.name || invitedUser.email || 'Unknown';

    // Add member
    groupBudget.addMember(invitedUser._id, userName, contributionPercentage || 0);
    await groupBudget.save();

    successResponse(res, 'Invite thành công', {
      groupBudget,
      invitedUser: {
        _id: invitedUser._id,
        name: userName,
        email: invitedUser.email,
      }
    }, 200);
  } catch (error) {
    console.error('❌ Invite to GroupBudget error:', error);
    if (error instanceof BadRequestError || error instanceof NotFoundError || error instanceof ForbiddenError) {
      throw error;
    }
    throw new BadRequestError(error.message);
  }
};

/**
 * @desc    Update group budget
 * @route   PUT /api/group-budgets/:id
 * @access  Private
 */
export const updateGroupBudget = async (req, res) => {
  const userId = req.userId;
  const { id } = req.params;
  const updates = req.body;

  try {
    const groupBudget = await GroupBudget.findById(id);
    if (!groupBudget) {
      throw new NotFoundError('Không tìm thấy GroupBudget');
    }

    // Only creator or members can update
    const isMember = groupBudget.members.some(m => m.userId.toString() === userId.toString());
    const isCreator = groupBudget.createdBy.toString() === userId.toString();

    if (!isMember && !isCreator) {
      throw new ForbiddenError('Bạn không có quyền cập nhật budget này');
    }

    // Allowed fields to update
    const allowedUpdates = ['name', 'description', 'totalBudget', 'endDate', 'autoSplitByContribution', 'allowPartialTag'];
    Object.keys(updates).forEach(key => {
      if (allowedUpdates.includes(key)) {
        groupBudget[key] = updates[key];
      }
    });

    await groupBudget.save();

    successResponse(res, 'Cập nhật GroupBudget thành công', groupBudget);
  } catch (error) {
    console.error('❌ Update GroupBudget error:', error);
    if (error instanceof NotFoundError || error instanceof ForbiddenError) {
      throw error;
    }
    throw new BadRequestError(error.message);
  }
};

/**
 * @desc    Delete group budget
 * @route   DELETE /api/group-budgets/:id
 * @access  Private
 */
export const deleteGroupBudget = async (req, res) => {
  const userId = req.userId;
  const { id } = req.params;

  try {
    const groupBudget = await GroupBudget.findById(id);
    if (!groupBudget) {
      throw new NotFoundError('Không tìm thấy GroupBudget');
    }

    // Only creator can delete
    if (groupBudget.createdBy.toString() !== userId.toString()) {
      throw new ForbiddenError('Chỉ người tạo mới có thể xóa budget này');
    }

    await GroupBudget.findByIdAndDelete(id);

    successResponse(res, null, 'Xóa GroupBudget thành công');
  } catch (error) {
    console.error('❌ Delete GroupBudget error:', error);
    if (error instanceof NotFoundError || error instanceof ForbiddenError) {
      throw error;
    }
    throw new BadRequestError(error.message);
  }
};

// ===== Expense operations (keep same as before) =====

/**
 * @desc    Add expense to group budget
 * @route   POST /api/group-budgets/:id/expenses
 * @access  Private
 */
export const addExpenseToGroupBudget = async (req, res) => {
  const userId = req.userId;
  const { id } = req.params;
  const { description, amount, category, date, splitType, participantUserIds, customSplits, location, notes, receiptUrl } = req.body;

  try {
    const groupBudget = await GroupBudget.findById(id);
    if (!groupBudget) {
      throw new NotFoundError('Không tìm thấy GroupBudget');
    }

    // Check if user is member
    const member = groupBudget.members.find(m => m.userId.toString() === userId.toString());
    if (!member) {
      throw new ForbiddenError('Bạn không phải thành viên của budget này');
    }

    // Estimate user's share for personal expense record
    const estimatedShare = splitType === 'equal'
      ? amount / groupBudget.members.length
      : amount * (member.contributionPercentage / 100);

    // Option B: Create personal Expense record first
    const personalExpense = new Expense({
      userId,
      title: `${description} (${groupBudget.name})`,
      description: `Group expense from ${groupBudget.name}`,
      amount,
      category: category || 'other',
      date: date || new Date(),
      groupBudgetId: groupBudget._id,
      isGroupExpense: true,
      groupShareAmount: estimatedShare,
      // Don't include location (expects object) and receiptUrl - they're stored in GroupBudget expense
    });

    await personalExpense.save();

    // Add to GroupBudget
    const expenseData = {
      description,
      amount,
      paidBy: userId,  // Who paid for this expense
      category: category || 'other',
      date: date || new Date(),
      splitType: splitType || 'auto',
      participants: participantUserIds || [],  // Changed from participantUserIds to participants
      customSplits: customSplits || [],
      location,
      notes,
      receiptUrl,
    };

    const expense = groupBudget.addExpense(expenseData, personalExpense._id);
    await groupBudget.save();

    // Update personal expense with accurate share
    const actualSplit = expense.splits.find(s => s.userId.toString() === userId.toString());
    if (actualSplit) {
      personalExpense.groupShareAmount = actualSplit.amount;
      await personalExpense.save();
    }

    successResponse(res, 'Thêm expense thành công', {
      groupBudget,
      expense,
      personalExpense,
    }, 201);
  } catch (error) {
    console.error('❌ Add expense error:', error);
    if (error instanceof NotFoundError || error instanceof ForbiddenError || error instanceof BadRequestError) {
      throw error;
    }
    throw new BadRequestError(error.message);
  }
};

// Record funding contribution
export const recordFunding = async (req, res) => {
  const { id } = req.params;
  const { userId, amount } = req.body;

  const groupBudget = await GroupBudget.findById(id);
  if (!groupBudget) {
    throw new NotFoundError('GroupBudget không tồn tại');
  }

  const member = groupBudget.members.find(m => m.userId.toString() === userId);
  if (!member) {
    throw new BadRequestError('User không phải thành viên');
  }

  member.funded += amount;
  groupBudget.totalFunded += amount;
  await groupBudget.save();

  return successResponse(res, 'Ghi nhận đóng góp thành công', groupBudget);
};

// Record payment/settlement
export const recordPayment = async (req, res) => {
  const { id } = req.params;
  const { fromUserId, toUserId, amount } = req.body;

  const groupBudget = await GroupBudget.findById(id);
  if (!groupBudget) {
    throw new NotFoundError('GroupBudget không tồn tại');
  }

  const fromMember = groupBudget.members.find(m => m.userId.toString() === fromUserId);
  const toMember = groupBudget.members.find(m => m.userId.toString() === toUserId);

  if (!fromMember || !toMember) {
    throw new BadRequestError('User không phải thành viên');
  }

  fromMember.balance += amount;
  toMember.balance -= amount;
  await groupBudget.save();

  return successResponse(res, 'Ghi nhận thanh toán thành công', groupBudget);
};

// Get settlement plan
export const getSettlementPlan = async (req, res) => {
  const { id } = req.params;

  const groupBudget = await GroupBudget.findById(id);
  if (!groupBudget) {
    throw new NotFoundError('GroupBudget không tồn tại');
  }

  const debtors = groupBudget.members.filter(m => m.balance < 0);
  const creditors = groupBudget.members.filter(m => m.balance > 0);

  const settlements = [];
  let i = 0, j = 0;

  while (i < debtors.length && j < creditors.length) {
    const debt = Math.abs(debtors[i].balance);
    const credit = creditors[j].balance;
    const amount = Math.min(debt, credit);

    settlements.push({
      from: debtors[i].userId,
      to: creditors[j].userId,
      amount
    });

    debtors[i].balance += amount;
    creditors[j].balance -= amount;

    if (Math.abs(debtors[i].balance) < 0.01) i++;
    if (Math.abs(creditors[j].balance) < 0.01) j++;
  }

  return successResponse(res, 'Kế hoạch thanh toán', { settlements });
};

// Settle group budget
export const settleGroupBudget = async (req, res) => {
  const { id } = req.params;

  const groupBudget = await GroupBudget.findById(id);
  if (!groupBudget) {
    throw new NotFoundError('GroupBudget không tồn tại');
  }

  groupBudget.isSettled = true;
  groupBudget.isActive = false;
  groupBudget.members.forEach(m => m.balance = 0);
  await groupBudget.save();

  return successResponse(res, 'Đã thanh toán xong GroupBudget', groupBudget);
};

// Get group budget summary
export const getGroupBudgetSummary = async (req, res) => {
  const { id } = req.params;

  const groupBudget = await GroupBudget.findById(id)
    .populate('members.userId', 'profile.name email')
    .populate('expenses.paidBy', 'profile.name');

  if (!groupBudget) {
    throw new NotFoundError('GroupBudget không tồn tại');
  }

  const summary = {
    id: groupBudget._id,
    name: groupBudget.name,
    totalBudget: groupBudget.totalBudget,
    totalSpent: groupBudget.totalSpent,
    totalFunded: groupBudget.totalFunded,
    remaining: groupBudget.remaining,
    memberCount: groupBudget.members.length,
    expenseCount: groupBudget.expenses.length,
    isSettled: groupBudget.isSettled,
    members: groupBudget.members.map(m => ({
      userId: m.userId._id || m.userId,
      name: m.userId.profile?.name || m.userId.email,
      contribution: m.contributionPercentage,
      funded: m.funded,
      spent: m.spent,
      balance: m.balance
    }))
  };

  return successResponse(res, 'Tổng quan GroupBudget', summary);
};