export const VietnameseText = {
  // App Name
  appName: 'ZBudget',

  // Onboarding
  onboarding: {
    title1: '💰 Theo dõi chi tiêu dễ dàng',
    description1: 'Quét hoá đơn offline và phân loại tự động chi tiêu của bạn',
    title2: '🎯 Thử thách tiết kiệm vui nhộn',
    description2: 'Tham gia thử thách micro-savings và nhận huy hiệu emoji cute',
    title3: '👥 Quản lý ngân sách nhóm',
    description3: 'Chia sẻ chi phí với bạn bè và theo dõi ngân sách chung một cách dễ dàng',
    next: 'Tiếp theo',
    skip: 'Bỏ qua',
    getStarted: 'Bắt đầu ngay',
  },

  // Authentication
  auth: {
    welcomeBack: 'Chào mừng trở lại! 👋',
    emailOrPhone: 'Email hoặc số điện thoại',
    password: 'Mật khẩu',
    forgotPassword: 'Quên mật khẩu?',
    login: 'Đăng nhập',
    biometricLogin: '🔒 Đăng nhập bằng sinh trắc học',
    or: 'hoặc',
    googleLogin: '🌐 Đăng nhập với Google',
    zaloLogin: '💬 Đăng nhập với Zalo',
    noAccount: 'Chưa có tài khoản? Đăng ký ngay',
    createAccount: 'Tạo tài khoản mới',
    fullName: 'Họ và tên',
    email: 'Email',
    phone: 'Số điện thoại',
    confirmPassword: 'Xác nhận mật khẩu',
    agreeTerms: 'Tôi đồng ý với Điều khoản sử dụng và Chính sách bảo mật',
    signUp: 'Đăng ký',
    hasAccount: 'Đã có tài khoản? Đăng nhập',
  },

  // Home Dashboard
  home: {
    greeting: 'Xin chào, {name}! 👋',
    monthlyBudget: 'Ngân sách tháng này',
    quickActions: 'Thao tác nhanh',
    addExpense: 'Thêm chi tiêu',
    scanReceipt: 'Quét hoá đơn',
    viewBudget: 'Xem ngân sách',
    challenges: 'Thử thách',
    recentExpenses: 'Chi tiêu gần đây',
    currentChallenge: 'Thử thách hiện tại',
    savings: 'Tiết kiệm',
    balance: 'Số dư tháng này',
    dailyBudget: 'Ngân sách hàng ngày',
    savingsGoal: 'Mục tiêu tiết kiệm',
    target: 'Mục tiêu',
    features: 'Thêm tính năng',
    groups: 'Nhóm',
    shareExpenses: 'Chia sẻ chi phí',
    savingsFun: 'Tiết kiệm vui',
    settings: 'Cài đặt',
    customizeApp: 'Tùy chỉnh app',
    premium: 'Premium',
    advancedFeatures: 'Tính năng nâng cao',
    transactionHistory: 'Lịch sử giao dịch',
    seeAll: 'Xem tất cả',
    loadingDashboard: 'Đang tải dữ liệu dashboard...',
    profile: 'Profile',
    notifications: 'Thông báo',
    logout: 'Đăng xuất',
    logoutConfirm: 'Bạn có chắc chắn muốn đăng xuất khỏi ứng dụng?',
    logoutProcessing: 'Đang đăng xuất...',
  },

  // Expense Categories
  categories: {
    food: 'Ăn uống',
    transport: 'Di chuyển',
    shopping: 'Mua sắm',
    entertainment: 'Giải trí',
    healthcare: 'Y tế',
    education: 'Giáo dục',
    utilities: 'Tiện ích',
    other: 'Khác',
  },

  // Currency
  currency: {
    vnd: 'VND',
    usd: 'USD',
    eur: 'EUR',
  },

  // Common Actions
  actions: {
    save: 'Lưu',
    cancel: 'Hủy',
    delete: 'Xóa',
    edit: 'Chỉnh sửa',
    add: 'Thêm',
    confirm: 'Xác nhận',
    back: 'Quay lại',
    next: 'Tiếp theo',
    done: 'Hoàn thành',
    retry: 'Thử lại',
    close: 'Đóng',
    agree: 'Đồng ý',
    processing: 'Đang xử lý...',
    loading: 'Đang tải...',
    success: 'Thành công',
    error: 'Lỗi',
    warning: 'Cảnh báo',
  },

  // AI Chatbot
  chatbot: {
    welcome: 'Xin chào! Tôi có thể giúp bạn ghi lại chi tiêu như thế nào?',
    askAmount: 'Bạn đã chi bao nhiều tiền?',
    askCategory: 'Khoản chi này thuộc danh mục nào?',
    askDate: 'Khi nào bạn chi tiền này?',
    confirmExpense: 'Xác nhận ghi lại chi tiêu {amount} VND cho {category}?',
    expenseSaved: 'Đã lưu chi tiêu thành công! 💰',
    voicePrompt: 'Nói về khoản chi tiêu của bạn...',
    processing: 'Đang xử lý...',
  },

  // Budget
  budget: {
    myBudget: 'Ngân sách của tôi',
    totalBudget: 'Tổng ngân sách tháng',
    spent: 'Đã chi',
    remaining: 'Còn lại',
    createBudget: 'Tạo ngân sách',
    editBudget: 'Chỉnh sửa ngân sách',
    budgetTemplates: 'Mẫu có sẵn',
    student: 'Sinh viên',
    office: 'Nhân viên văn phòng',
    freelancer: 'Tự do',
    customBudget: 'Tạo ngân sách tùy chỉnh',
    allocateByCategory: 'Phân bổ theo danh mục',
    warning: 'Cảnh báo: Bạn đã chi {percent}% ngân sách {category}!',
  },

  // Navigation
  navigation: {
    home: 'Trang chủ',
    budget: 'Ngân sách',
    group: 'Nhóm',
    reports: 'Báo cáo',
    settings: 'Cài đặt',
    chat: 'Trò chuyện',
  },

  // Settings
  settings: {
    profile: 'Thông tin cá nhân',
    account: 'Tài khoản',
    changePassword: 'Đổi mật khẩu',
    security: 'Bảo mật',
    language: 'Ngôn ngữ',
    darkMode: 'Chế độ tối',
    notifications: 'Thông báo',
    momoIntegration: 'Liên kết Momo',
    premium: 'Nâng cấp Premium',
    help: 'Trung tâm trợ giúp',
    contact: 'Liên hệ hỗ trợ',
    rateApp: 'Đánh giá ứng dụng',
    terms: 'Điều khoản sử dụng',
    privacy: 'Chính sách bảo mật',
    logout: 'Đăng xuất',
    version: 'Phiên bản',
  },

  // Screen titles
  screens: {
    dashboard: 'Dashboard',
    profile: 'Hồ sơ cá nhân',
    addExpense: 'Thêm chi tiêu',
    expenseDetail: 'Chi tiết chi tiêu',
    scanReceipt: 'Quét hoá đơn',
    chat: 'Trợ lý AI',
    inviteMembers: 'Mời thành viên',
    createBudget: 'Tạo ngân sách',
    editBudget: 'Chỉnh sửa ngân sách',
    budgetList: 'Danh sách ngân sách',
    groupList: 'Danh sách nhóm',
    createGroup: 'Tạo nhóm',
    reports: 'Báo cáo',
    challenge: 'Thử thách',
    premium: 'Premium',
    settings: 'Cài đặt',
  },

  // Error messages
  errors: {
    networkError: 'Lỗi kết nối mạng. Vui lòng kiểm tra kết nối internet.',
    storageError: 'Lỗi lưu trữ dữ liệu. Vui lòng thử lại.',
    validationError: 'Dữ liệu không hợp lệ. Vui lòng kiểm tra lại.',
    authError: 'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',
    unknownError: 'Đã xảy ra lỗi không mong muốn',
    addExpenseFailed: 'Không thể thêm chi tiêu. Vui lòng thử lại.',
    updateExpenseFailed: 'Không thể cập nhật chi tiêu. Vui lòng thử lại.',
    deleteExpenseFailed: 'Không thể xóa chi tiêu. Vui lòng thử lại.',
    loginFailed: 'Đăng nhập thất bại. Vui lòng thử lại.',
    logoutFailed: 'Đăng xuất thất bại. Vui lòng thử lại.',
    initAppFailed: 'Không thể khởi tạo ứng dụng. Vui lòng thử lại.',
  },

  // Status messages
  status: {
    inDevelopment: 'Tính năng đang được phát triển',
    comingSoon: 'Sắp ra mắt',
    offline: 'Hoạt động offline',
    accuracy: 'Độ chính xác',
    autoCategory: 'Tự động phân loại',
    vietnameseSupport: 'Hỗ trợ Tiếng Việt',
  },

  // Challenges
  challenges: {
    title: '🏆 Thử thách tiết kiệm',
    subtitle: 'Biến tiết kiệm thành thói quen vui nhộn',
    currentChallenge: 'Thử thách hiện tại',
    userStats: 'Thống kê cá nhân',
    level: 'Cấp độ',
    streak: 'Chuỗi thành công',
    points: 'Điểm',
    streakMessages: {
      superstar: 'Siêu sao tiết kiệm! 🌟',
      expert: 'Chuyên gia tiết kiệm! 💎',
      progressing: 'Đang tiến bộ tốt! 🚀',
      beginner: 'Hãy bắt đầu chuỗi thành công! 💪',
    },
    tabs: {
      active: 'Đang tham gia',
      available: 'Có thể tham gia',
      completed: 'Hoàn thành',
    },
    difficulty: {
      easy: 'Dễ',
      medium: 'Trung bình',
      hard: 'Khó',
    },
    status: {
      inProgress: 'Đang diễn ra',
      join: 'Tham gia ngay',
      completed: 'Đã hoàn thành',
      progress: '{percent}% hoàn thành',
    },
    actions: {
      share: 'Chia sẻ',
      leaderboard: 'Bảng xếp hạng',
      joinNow: 'Tham gia ngay',
    },
    progress: {
      saved: 'Đã tiết kiệm',
      remaining: '{days} ngày còn lại',
      target: 'Mục tiêu tiết kiệm',
      reward: '+{points} điểm khi hoàn thành',
    },
    categories: {
      drinks: '🧋 Thử thách đồ uống',
      food: '🍜 Thử thách ăn uống',
      transport: '🚌 Thử thách di chuyển',
      shopping: '🛍️ Thử thách mua sắm',
      entertainment: '🎬 Thử thách giải trí',
      special: '🏮 Thử thách đặc biệt Việt Nam',
      digital: '📱 Thử thách công nghệ',
    },
    participants: '{count} người tham gia',
    duration: 'Thời gian: {duration}',
    pointsReward: '{points} điểm',
  },

  // Premium
  premium: {
    title: 'ZBudget Premium',
    price: '45,000 VND/tháng',
    valueProposition: 'Chỉ 1,500 VND/ngày để quản lý tài chính thông minh hơn!',
    features: {
      unlimitedScanning: 'Quét không giới hạn hoá đơn',
      advancedAI: 'AI thông minh nâng cao',
      customThemes: 'Chủ đề tùy chỉnh',
      prioritySupport: 'Hỗ trợ ưu tiên 24/7',
      advancedReports: 'Báo cáo chi tiết',
      investmentAdvice: 'Lời khuyên đầu tư từ AI',
    },
    freeTrial: 'Dùng thử miễn phí 7 ngày',
    startTrial: 'Bắt đầu dùng thử',
    buyPremium: 'Mua Premium',
    cancelAnytime: 'Hủy bất cứ lúc nào',
  },
};
